variable "filename" {
   default = "/home/ubuntu/terrraform-course/terraform-variables/devops-automated.txt"
}



variable "content" {
   default = "Autogenerated"
}

variable "devops_op_trainer" {}


